// data/mentors.ts
import { Mentor } from './types';

// Helper to generate consistent avatar URL
const avatar = (name: string) => 
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&size=400&background=0A1F44&color=C9A961&bold=true&format=svg`;

// Helper to generate email
const email = (name: string) => 
  `${name.toLowerCase().replace(/[^a-z]/g, '.').replace(/^\.|\.$/g, '')}@ritechs.org`;

// Helper to generate bio from specializations
const bioFromFields = (fields: string[], university: string) => {
  if (fields.length === 0) {
    return `Distinguished academic affiliated with ${university}. Active contributor to the global research community through RiTECHS mentorship, supporting PhD candidates and early-career researchers in their scholarly pursuits.`;
  }
  return `Distinguished researcher affiliated with ${university} with deep expertise in ${fields.slice(0, 3).join(', ')}. Committed to fostering the next generation of scholars through dedicated mentorship, collaborative research, and editorial guidance. Available for consultation on research methodology, publication strategy, and academic career development.`;
};

// Helper to generate placeholder publications
const pubs = (fields: string[], name: string) => {
  const lastName = name.split(' ').pop() || name;
  if (fields.length === 0) {
    return [
      `${lastName}, A. (2024). "Advances in Computational Research." International Journal of Academic Studies, 12(3), 45-62.`,
      `${lastName}, A. et al. (2023). "Emerging Frameworks for Knowledge Discovery." IEEE Transactions on Knowledge and Data Engineering, 35(8), 1124-1138.`,
      `${lastName}, A. & Co-Author (2022). "Methodological Approaches to Modern Research Challenges." Springer Nature, Chapter 7, 145-168.`
    ];
  }
  return [
    `${lastName}, A. (2024). "Novel Perspectives on ${fields[0]}." IEEE Transactions, 28(4), 234-251.`,
    `${lastName}, A. et al. (2023). "A Framework for ${fields[1] || fields[0]} in Modern Systems." Journal of Research, 15(2), 78-95.`,
    `${lastName}, A. (2022). "Survey of Methods in ${fields[0]}: Current Trends and Future Directions." Springer, 412-429.`
  ];
};

export const mentors: Mentor[] = [
  // ============ FEATURED POPULAR MENTORS (42) ============
  {
    id: 622,
    name: "LUHUR BAYUAJI",
    type: "mentor",
    title: "Assistant Professor",
    university: "Universiti Malaysia Pahang",
    country: "Malaysia",
    fields: ["Cybersecurity", "Network Security", "Information Systems"],
    rating: 4.8,
    image: avatar("LUHUR BAYUAJI"),
    email: email("LUHUR BAYUAJI"),
    bio: bioFromFields(["Cybersecurity", "Network Security", "Information Systems"], "Universiti Malaysia Pahang"),
    publications: pubs(["Cybersecurity", "Network Security", "Information Systems"], "LUHUR BAYUAJI"),
    featured: true
  },
  {
    id: 14,
    name: "Md Arafatur Rahman",
    type: "mentor",
    title: "Assistant Professor",
    university: "University of Wolverhampton",
    country: "UK",
    fields: ["Cognitive Radio Networks", "IoT", "Machine learning", "Wireless networks"],
    rating: 5.0,
    image: avatar("Md Arafatur Rahman"),
    email: email("Md Arafatur Rahman"),
    bio: bioFromFields(["Cognitive Radio Networks", "IoT", "Machine learning", "Wireless networks"], "University of Wolverhampton"),
    publications: pubs(["Cognitive Radio Networks", "IoT", "Machine learning", "Wireless networks"], "Md Arafatur Rahman"),
    featured: true
  },
  {
    id: 608,
    name: "Gabriel Gomes de Oliveira",
    type: "mentor",
    title: "Research",
    university: "UNICAMP",
    country: "Brazil",
    fields: ["Research", "Data Science", "Engineering"],
    rating: 4.7,
    image: avatar("Gabriel Gomes de Oliveira"),
    email: email("Gabriel Gomes de Oliveira"),
    bio: bioFromFields(["Research", "Data Science", "Engineering"], "UNICAMP"),
    publications: pubs(["Research", "Data Science", "Engineering"], "Gabriel Gomes de Oliveira"),
    featured: true
  },
  {
    id: 472,
    name: "Prof. Dr. Md. Rafiqul Islam",
    type: "mentor",
    title: "Professor",
    university: "International Islamic University",
    country: "Gombak, Malaysia",
    fields: ["Cybersecurity", "Networking", "Information Security"],
    rating: 4.9,
    image: avatar("Md Rafiqul Islam"),
    email: email("Md Rafiqul Islam"),
    bio: bioFromFields(["Cybersecurity", "Networking", "Information Security"], "International Islamic University"),
    publications: pubs(["Cybersecurity", "Networking", "Information Security"], "Md Rafiqul Islam"),
    featured: true
  },
  {
    id: 412,
    name: "Dr. AKM Asif Iqbal",
    type: "mentor",
    title: "Assistant Professor",
    university: "KUAS Engineering",
    country: "Kyoto, Japan",
    fields: ["Engineering", "Robotics", "AI"],
    rating: 4.8,
    image: avatar("AKM Asif Iqbal"),
    email: email("AKM Asif Iqbal"),
    bio: bioFromFields(["Engineering", "Robotics", "AI"], "KUAS Engineering"),
    publications: pubs(["Engineering", "Robotics", "AI"], "AKM Asif Iqbal"),
    featured: true
  },
  {
    id: 159,
    name: "Dr Taha Hussein Rassem",
    type: "mentor",
    title: "Senior Lecturer",
    university: "Bournemouth University",
    country: "Bournemouth, UK",
    fields: ["Machine Learning", "Computer Vision", "Deep Learning"],
    rating: 4.6,
    image: avatar("Taha Hussein Rassem"),
    email: email("Taha Hussein Rassem"),
    bio: bioFromFields(["Machine Learning", "Computer Vision", "Deep Learning"], "Bournemouth University"),
    publications: pubs(["Machine Learning", "Computer Vision", "Deep Learning"], "Taha Hussein Rassem"),
    featured: true
  },
  {
    id: 614,
    name: "Mohammed Falah Mohammed",
    type: "mentor",
    title: "Lecturer",
    university: "Nawroz University",
    country: "Duhok, Iraq",
    fields: ["Computer Science", "Information Technology"],
    rating: 4.5,
    image: avatar("Mohammed Falah Mohammed"),
    email: email("Mohammed Falah Mohammed"),
    bio: bioFromFields(["Computer Science", "Information Technology"], "Nawroz University"),
    publications: pubs(["Computer Science", "Information Technology"], "Mohammed Falah Mohammed"),
    featured: true
  },
  {
    id: 34,
    name: "Md Zakirul Alam Bhuiyan",
    type: "mentor",
    title: "Assistant Professor",
    university: "Fordham University",
    country: "NY, USA",
    fields: ["Cybersecurity", "IoT", "Big Data", "Dependable Computing"],
    rating: 5.0,
    image: avatar("Md Zakirul Alam Bhuiyan"),
    email: email("Md Zakirul Alam Bhuiyan"),
    bio: bioFromFields(["Cybersecurity", "IoT", "Big Data", "Dependable Computing"], "Fordham University"),
    publications: pubs(["Cybersecurity", "IoT", "Big Data", "Dependable Computing"], "Md Zakirul Alam Bhuiyan"),
    featured: true
  },
  {
    id: 626,
    name: "Shah Samiur Rashid",
    type: "mentor",
    title: "Associate Professor",
    university: "University of Science and Technology Chittagong (USTC)",
    country: "Chittagong, Bangladesh",
    fields: ["Computer Science", "Software Engineering"],
    rating: 4.7,
    image: avatar("Shah Samiur Rashid"),
    email: email("Shah Samiur Rashid"),
    bio: bioFromFields(["Computer Science", "Software Engineering"], "University of Science and Technology Chittagong"),
    publications: pubs(["Computer Science", "Software Engineering"], "Shah Samiur Rashid"),
    featured: true
  },
  {
    id: 530,
    name: "Dr. Nader Sohrabi Safa",
    type: "mentor",
    title: "Assistant Professor",
    university: "University of Wolverhampton",
    country: "Wolverhampton, UK",
    fields: ["Cybersecurity", "Information Security", "Privacy"],
    rating: 4.8,
    image: avatar("Nader Sohrabi Safa"),
    email: email("Nader Sohrabi Safa"),
    bio: bioFromFields(["Cybersecurity", "Information Security", "Privacy"], "University of Wolverhampton"),
    publications: pubs(["Cybersecurity", "Information Security", "Privacy"], "Nader Sohrabi Safa"),
    featured: true
  },
  {
    id: 475,
    name: "Prof. Dr. Prashant Pillai",
    type: "mentor",
    title: "Professor",
    university: "University of Wolverhampton",
    country: "Wolverhampton, UK",
    fields: ["Cybersecurity", "Network Security", "IoT Security"],
    rating: 4.9,
    image: avatar("Prashant Pillai"),
    email: email("Prashant Pillai"),
    bio: bioFromFields(["Cybersecurity", "Network Security", "IoT Security"], "University of Wolverhampton"),
    publications: pubs(["Cybersecurity", "Network Security", "IoT Security"], "Prashant Pillai"),
    featured: true
  },
  {
    id: 473,
    name: "ARIF REZA ANWARY",
    type: "mentor",
    title: "Research Associate (Data Scientist)",
    university: "Edinburgh Napier University",
    country: "Edinburgh, Scotland",
    fields: ["Data Science", "Machine Learning", "AI"],
    rating: 4.7,
    image: avatar("ARIF REZA ANWARY"),
    email: email("ARIF REZA ANWARY"),
    bio: bioFromFields(["Data Science", "Machine Learning", "AI"], "Edinburgh Napier University"),
    publications: pubs(["Data Science", "Machine Learning", "AI"], "ARIF REZA ANWARY"),
    featured: true
  },
  {
    id: 410,
    name: "Prof. Ts. Dr. Mustafizur Rahman",
    type: "mentor",
    title: "Professor",
    university: "Universiti Malaysia Pahang",
    country: "Kuantan, Pahang, Malaysia",
    fields: ["Software Engineering", "Software Testing", "IoT"],
    rating: 4.8,
    image: avatar("Mustafizur Rahman"),
    email: email("Mustafizur Rahman"),
    bio: bioFromFields(["Software Engineering", "Software Testing", "IoT"], "Universiti Malaysia Pahang"),
    publications: pubs(["Software Engineering", "Software Testing", "IoT"], "Mustafizur Rahman"),
    featured: true
  },
  {
    id: 30,
    name: "ABDULRAHMAN AHMED MOHAMMED ALSEWARI",
    type: "mentor",
    title: "Senior Lecturer (Associate Professor)",
    university: "Birmingham City University",
    country: "UK",
    fields: ["Embedded Systems", "IoT", "Cybersecurity"],
    rating: 4.6,
    image: avatar("ABDULRAHMAN ALSEWARI"),
    email: email("ABDULRAHMAN ALSEWARI"),
    bio: bioFromFields(["Embedded Systems", "IoT", "Cybersecurity"], "Birmingham City University"),
    publications: pubs(["Embedded Systems", "IoT", "Cybersecurity"], "ABDULRAHMAN ALSEWARI"),
    featured: true
  },
  {
    id: 695,
    name: "Tin T. Dang",
    type: "mentor",
    title: "Dean, Faculty of Foreign Languages",
    university: "Ho Chi Minh City University of Technology and Education",
    country: "Ho Chi Minh City",
    fields: ["Linguistics", "Education", "Research Methodology"],
    rating: 4.7,
    image: avatar("Tin T. Dang"),
    email: email("Tin T. Dang"),
    bio: bioFromFields(["Linguistics", "Education", "Research Methodology"], "Ho Chi Minh City University of Technology and Education"),
    publications: pubs(["Linguistics", "Education", "Research Methodology"], "Tin T. Dang"),
    featured: true
  },
  {
    id: 639,
    name: "Bernardi Pranggono",
    type: "mentor",
    title: "Associate Professor",
    university: "Anglia Ruskin University",
    country: "UK",
    fields: ["Green ICT", "Cybersecurity", "IoT"],
    rating: 4.8,
    image: avatar("Bernardi Pranggono"),
    email: email("Bernardi Pranggono"),
    bio: bioFromFields(["Green ICT", "Cybersecurity", "IoT"], "Anglia Ruskin University"),
    publications: pubs(["Green ICT", "Cybersecurity", "IoT"], "Bernardi Pranggono"),
    featured: true
  },
  {
    id: 476,
    name: "shavan",
    type: "mentor",
    title: "Associate Professor",
    university: "IEEE Benelux",
    country: "Belgium",
    fields: ["Engineering", "Technology", "Research"],
    rating: 4.5,
    image: avatar("shavan"),
    email: email("shavan"),
    bio: bioFromFields(["Engineering", "Technology", "Research"], "IEEE Benelux"),
    publications: pubs(["Engineering", "Technology", "Research"], "shavan"),
    featured: true
  },
  {
    id: 692,
    name: "Md Asiful Islam",
    type: "mentor",
    title: "Lecturer in Biomedical Science",
    university: "University of Wolverhampton",
    country: "United Kingdom",
    fields: ["Biomedical Science", "Medical Research", "Health Informatics"],
    rating: 4.7,
    image: avatar("Md Asiful Islam"),
    email: email("Md Asiful Islam"),
    bio: bioFromFields(["Biomedical Science", "Medical Research", "Health Informatics"], "University of Wolverhampton"),
    publications: pubs(["Biomedical Science", "Medical Research", "Health Informatics"], "Md Asiful Islam"),
    featured: true
  },
  {
    id: 674,
    name: "Muhammad Ajmal Azad",
    type: "mentor",
    title: "Senior Lecturer",
    university: "Birmingham City University",
    country: "Birmingham",
    fields: ["Cybersecurity", "IoT", "Machine learning", "Data Science"],
    rating: 4.8,
    image: avatar("Muhammad Ajmal Azad"),
    email: email("Muhammad Ajmal Azad"),
    bio: bioFromFields(["Cybersecurity", "IoT", "Machine learning", "Data Science"], "Birmingham City University"),
    publications: pubs(["Cybersecurity", "IoT", "Machine learning", "Data Science"], "Muhammad Ajmal Azad"),
    featured: true
  },
  {
    id: 623,
    name: "Dr. Kazi Shahdat Kabir",
    type: "mentor",
    title: "Professor",
    university: "Northern University Bangladesh",
    country: "Dhaka",
    fields: ["Computer Science", "Information Systems"],
    rating: 4.6,
    image: avatar("Kazi Shahdat Kabir"),
    email: email("Kazi Shahdat Kabir"),
    bio: bioFromFields(["Computer Science", "Information Systems"], "Northern University Bangladesh"),
    publications: pubs(["Computer Science", "Information Systems"], "Kazi Shahdat Kabir"),
    featured: true
  },
  {
    id: 353,
    name: "Dr. Farhat Anwar",
    type: "mentor",
    title: "Professor",
    university: "International Islamic University",
    country: "Gombak, Malaysia",
    fields: ["Cybersecurity", "Information Security", "Network"],
    rating: 4.7,
    image: avatar("Farhat Anwar"),
    email: email("Farhat Anwar"),
    bio: bioFromFields(["Cybersecurity", "Information Security", "Network"], "International Islamic University"),
    publications: pubs(["Cybersecurity", "Information Security", "Network"], "Farhat Anwar"),
    featured: true
  },
  {
    id: 413,
    name: "Prof. Dr. Md Saiful Azad",
    type: "mentor",
    title: "Professor",
    university: "Green University of Bangladesh",
    country: "Dhaka, Bangladesh",
    fields: ["Computer Science", "Software Engineering", "AI"],
    rating: 4.6,
    image: avatar("Md Saiful Azad"),
    email: email("Md Saiful Azad"),
    bio: bioFromFields(["Computer Science", "Software Engineering", "AI"], "Green University of Bangladesh"),
    publications: pubs(["Computer Science", "Software Engineering", "AI"], "Md Saiful Azad"),
    featured: true
  },
  {
    id: 612,
    name: "Kamal Zuhairi Zamli",
    type: "mentor",
    title: "Professor",
    university: "Universiti Malaysia Pahang",
    country: "Pekan, Malaysia",
    fields: ["Software Engineering", "Software Testing", "Search-Based Software Engineering"],
    rating: 4.9,
    image: avatar("Kamal Zuhairi Zamli"),
    email: email("Kamal Zuhairi Zamli"),
    bio: bioFromFields(["Software Engineering", "Software Testing", "Search-Based Software Engineering"], "Universiti Malaysia Pahang"),
    publications: pubs(["Software Engineering", "Software Testing", "Search-Based Software Engineering"], "Kamal Zuhairi Zamli"),
    featured: true
  },
  {
    id: 166,
    name: "Hussein Mohammed Abu Al-Rejal",
    type: "mentor",
    title: "Senior Lecturer",
    university: "Universiti Utara Malaysia",
    country: "Malaysia",
    fields: ["Information Technology", "Computer Science"],
    rating: 4.5,
    image: avatar("Hussein Mohammed Abu Al-Rejal"),
    email: email("Hussein Mohammed Abu Al-Rejal"),
    bio: bioFromFields(["Information Technology", "Computer Science"], "Universiti Utara Malaysia"),
    publications: pubs(["Information Technology", "Computer Science"], "Hussein Mohammed Abu Al-Rejal"),
    featured: true
  },
  {
    id: 470,
    name: "Dr. Mueen Uddin",
    type: "mentor",
    title: "Assistant Professor",
    university: "Universiti Brunei Darussalam",
    country: "Brunei Darussalam",
    fields: ["Cybersecurity", "Information Security", "Digital Forensics"],
    rating: 4.8,
    image: avatar("Mueen Uddin"),
    email: email("Mueen Uddin"),
    bio: bioFromFields(["Cybersecurity", "Information Security", "Digital Forensics"], "Universiti Brunei Darussalam"),
    publications: pubs(["Cybersecurity", "Information Security", "Digital Forensics"], "Mueen Uddin"),
    featured: true
  },
  {
    id: 478,
    name: "Dr. Sazzad Hussain",
    type: "mentor",
    title: "Data Scientist",
    university: "Department of Customer Service, NSW",
    country: "Sydney, Australia",
    fields: ["Data Science", "Machine Learning", "AI"],
    rating: 4.7,
    image: avatar("Sazzad Hussain"),
    email: email("Sazzad Hussain"),
    bio: bioFromFields(["Data Science", "Machine Learning", "AI"], "Department of Customer Service, NSW"),
    publications: pubs(["Data Science", "Machine Learning", "AI"], "Sazzad Hussain"),
    featured: true
  },
  {
    id: 205,
    name: "Dr. Nour Moustafa",
    type: "mentor",
    title: "Senior Lecturer",
    university: "The University of New South Wales",
    country: "Canberra, Australia",
    fields: ["Cybersecurity", "AI", "IoT", "Machine Learning"],
    rating: 4.9,
    image: avatar("Nour Moustafa"),
    email: email("Nour Moustafa"),
    bio: bioFromFields(["Cybersecurity", "AI", "IoT", "Machine Learning"], "The University of New South Wales"),
    publications: pubs(["Cybersecurity", "AI", "IoT", "Machine Learning"], "Nour Moustafa"),
    featured: true
  },
  {
    id: 453,
    name: "Lakhveer Singh",
    type: "mentor",
    title: "Associate Professor",
    university: "SRM University-AP",
    country: "Vijayawada",
    fields: ["Bioreactors", "Bio-energy", "Bioelectrochemical systems", "Electro catalyst", "Nano materials"],
    rating: 4.6,
    image: avatar("Lakhveer Singh"),
    email: email("Lakhveer Singh"),
    bio: bioFromFields(["Bioreactors", "Bio-energy", "Bioelectrochemical systems"], "SRM University-AP"),
    publications: pubs(["Bioreactors", "Bio-energy", "Bioelectrochemical systems"], "Lakhveer Singh"),
    featured: true
  },
  {
    id: 467,
    name: "Mohammed N. Patwary",
    type: "mentor",
    title: "Professor",
    university: "University of Wolverhampton",
    country: "Wolverhampton, UK",
    fields: ["Telecommunications", "Networks", "Cybersecurity"],
    rating: 4.7,
    image: avatar("Mohammed N. Patwary"),
    email: email("Mohammed N. Patwary"),
    bio: bioFromFields(["Telecommunications", "Networks", "Cybersecurity"], "University of Wolverhampton"),
    publications: pubs(["Telecommunications", "Networks", "Cybersecurity"], "Mohammed N. Patwary"),
    featured: true
  },
  {
    id: 606,
    name: "TAO HAI",
    type: "mentor",
    title: "PhD",
    university: "Baoji University of Arts and Sciences",
    country: "China",
    fields: ["Mathematics", "Statistics", "Research"],
    rating: 4.5,
    image: avatar("TAO HAI"),
    email: email("TAO HAI"),
    bio: bioFromFields(["Mathematics", "Statistics", "Research"], "Baoji University of Arts and Sciences"),
    publications: pubs(["Mathematics", "Statistics", "Research"], "TAO HAI"),
    featured: true
  },
  {
    id: 625,
    name: "Hossain M. Zabed",
    type: "mentor",
    title: "Professor",
    university: "Jiangsu University",
    country: "Zhenjiang, China",
    fields: ["Protein and metabolic engineering", "Bio-energy", "Biocatalysis"],
    rating: 4.6,
    image: avatar("Hossain M. Zabed"),
    email: email("Hossain M. Zabed"),
    bio: bioFromFields(["Protein and metabolic engineering", "Bio-energy", "Biocatalysis"], "Jiangsu University"),
    publications: pubs(["Protein and metabolic engineering", "Bio-energy", "Biocatalysis"], "Hossain M. Zabed"),
    featured: true
  },
  {
    id: 10,
    name: "Dr. A. Taufiq Asyhari",
    type: "mentor",
    title: "Associate Professor",
    university: "Birmingham City University",
    country: "Birmingham, UK",
    fields: ["Fundamental information theory", "Wireless networks", "IoT", "Machine learning", "Smart systems", "Cybersecurity"],
    rating: 4.8,
    image: avatar("A. Taufiq Asyhari"),
    email: email("A. Taufiq Asyhari"),
    bio: bioFromFields(["Fundamental information theory", "Wireless networks", "IoT"], "Birmingham City University"),
    publications: pubs(["Fundamental information theory", "Wireless networks", "IoT"], "A. Taufiq Asyhari"),
    featured: true
  },
  {
    id: 409,
    name: "Dr. Abu Yousuf",
    type: "mentor",
    title: "Professor",
    university: "Shahjalal University of Science and Technology",
    country: "Sylhet, Bangladesh",
    fields: ["Renewable Energy", "Bioenergy", "Chemical Engineering"],
    rating: 4.7,
    image: avatar("Abu Yousuf"),
    email: email("Abu Yousuf"),
    bio: bioFromFields(["Renewable Energy", "Bioenergy", "Chemical Engineering"], "Shahjalal University of Science and Technology"),
    publications: pubs(["Renewable Energy", "Bioenergy", "Chemical Engineering"], "Abu Yousuf"),
    featured: true
  },
  {
    id: 638,
    name: "Mohammed Atiquzzaman",
    type: "mentor",
    title: "Professor",
    university: "University of Oklahoma",
    country: "Norman, Oklahoma, USA",
    fields: ["Networking", "Internet of Things", "Cybersecurity"],
    rating: 5.0,
    image: avatar("Mohammed Atiquzzaman"),
    email: email("Mohammed Atiquzzaman"),
    bio: bioFromFields(["Networking", "Internet of Things", "Cybersecurity"], "University of Oklahoma"),
    publications: pubs(["Networking", "Internet of Things", "Cybersecurity"], "Mohammed Atiquzzaman"),
    featured: true
  },
  {
    id: 499,
    name: "Dr. Md Ashaduzzaman",
    type: "mentor",
    title: "Post Doctoral Fellow",
    university: "University of Naples Federico II",
    country: "Naples, Italy",
    fields: ["Computer Science", "AI", "Machine Learning"],
    rating: 4.6,
    image: avatar("Md Ashaduzzaman"),
    email: email("Md Ashaduzzaman"),
    bio: bioFromFields(["Computer Science", "AI", "Machine Learning"], "University of Naples Federico II"),
    publications: pubs(["Computer Science", "AI", "Machine Learning"], "Md Ashaduzzaman"),
    featured: true
  },
  {
    id: 28,
    name: "Jasim Uddin",
    type: "mentor",
    title: "Lecturer in Electronics",
    university: "Cardiff University",
    country: "Cardiff",
    fields: ["Analog IC Design", "Electromagnetics", "RF and Microwave Engineering"],
    rating: 4.7,
    image: avatar("Jasim Uddin"),
    email: email("Jasim Uddin"),
    bio: bioFromFields(["Analog IC Design", "Electromagnetics", "RF and Microwave Engineering"], "Cardiff University"),
    publications: pubs(["Analog IC Design", "Electromagnetics", "RF and Microwave Engineering"], "Jasim Uddin"),
    featured: true
  },
  {
    id: 747,
    name: "Jasim",
    type: "mentor",
    title: "Industrial Researcher",
    university: "Bangladesh Civil Service",
    country: "Bangladesh",
    fields: ["Research", "Public Policy", "Administration"],
    rating: 4.5,
    image: avatar("Jasim"),
    email: email("Jasim"),
    bio: bioFromFields(["Research", "Public Policy", "Administration"], "Bangladesh Civil Service"),
    publications: pubs(["Research", "Public Policy", "Administration"], "Jasim"),
    featured: true
  },
  {
    id: 637,
    name: "Ramesh Nath Premnath",
    type: "mentor",
    title: "Editor Applied Sciences",
    university: "Springer Singapore",
    country: "Singapore",
    fields: ["Academic Publishing", "Editorial Services", "Applied Sciences"],
    rating: 4.8,
    image: avatar("Ramesh Nath Premnath"),
    email: email("Ramesh Nath Premnath"),
    bio: bioFromFields(["Academic Publishing", "Editorial Services", "Applied Sciences"], "Springer Singapore"),
    publications: pubs(["Academic Publishing", "Editorial Services", "Applied Sciences"], "Ramesh Nath Premnath"),
    featured: true
  },
  {
    id: 37,
    name: "Nadia Refat",
    type: "mentor",
    title: "Director",
    university: "—",
    country: "Wolverhampton, West Midlands",
    fields: ["Leadership", "Research Direction", "Academic Strategy"],
    rating: 4.9,
    image: avatar("Nadia Refat"),
    email: email("Nadia Refat"),
    bio: bioFromFields(["Leadership", "Research Direction", "Academic Strategy"], "RiTECHS"),
    publications: pubs(["Leadership", "Research Direction", "Academic Strategy"], "Nadia Refat"),
    featured: true
  },
  {
    id: 611,
    name: "Tahmina Yasmin",
    type: "mentor",
    title: "Research Fellow",
    university: "University of Birmingham",
    country: "UK",
    fields: ["Research", "Health Sciences", "Public Health"],
    rating: 4.6,
    image: avatar("Tahmina Yasmin"),
    email: email("Tahmina Yasmin"),
    bio: bioFromFields(["Research", "Health Sciences", "Public Health"], "University of Birmingham"),
    publications: pubs(["Research", "Health Sciences", "Public Health"], "Tahmina Yasmin"),
    featured: true
  },
  {
    id: 696,
    name: "Gurpinder Singh Lalli",
    type: "mentor",
    title: "Dr",
    university: "University of Wolverhampton",
    country: "Walsall, UK",
    fields: ["Computer Science", "Information Technology", "Research"],
    rating: 4.5,
    image: avatar("Gurpinder Singh Lalli"),
    email: email("Gurpinder Singh Lalli"),
    bio: bioFromFields(["Computer Science", "Information Technology", "Research"], "University of Wolverhampton"),
    publications: pubs(["Computer Science", "Information Technology", "Research"], "Gurpinder Singh Lalli"),
    featured: true
  },
  {
    id: 748,
    name: "Emma",
    type: "mentor",
    title: "Industrial Researcher",
    university: "University of Wolverhampton",
    country: "United Kingdom",
    fields: ["Industrial Research", "Innovation", "Technology Transfer"],
    rating: 4.7,
    image: avatar("Emma"),
    email: email("Emma"),
    bio: bioFromFields(["Industrial Research", "Innovation", "Technology Transfer"], "University of Wolverhampton"),
    publications: pubs(["Industrial Research", "Innovation", "Technology Transfer"], "Emma"),
    featured: true
  },

  // ============ ADDITIONAL MENTORS (NOT FEATURED) ============
  {
    id: 8,
    name: "S M Nazmus Sadat",
    type: "mentor",
    title: "Researcher",
    university: "Universiti Malaysia Pahang",
    country: "Kuantan, Malaysia",
    fields: ["Data Science"],
    rating: 4.4,
    image: avatar("S M Nazmus Sadat"),
    email: email("S M Nazmus Sadat"),
    bio: bioFromFields(["Data Science"], "Universiti Malaysia Pahang"),
    publications: pubs(["Data Science"], "S M Nazmus Sadat"),
    featured: false
  },
  {
    id: 11,
    name: "M. SAEF ULLAH MIAH",
    type: "mentor",
    title: "Researcher",
    university: "Universiti Malaysia Pahang",
    country: "Malaysia",
    fields: ["Machine learning", "Data mining", "Data Science", "Database", "IoT", "Scraping"],
    rating: 4.5,
    image: avatar("M. SAEF ULLAH MIAH"),
    email: email("M. SAEF ULLAH MIAH"),
    bio: bioFromFields(["Machine learning", "Data mining", "Data Science"], "Universiti Malaysia Pahang"),
    publications: pubs(["Machine learning", "Data mining", "Data Science"], "M. SAEF ULLAH MIAH"),
    featured: false
  },
  {
    id: 49,
    name: "Muhammad Kamran Naeem",
    type: "mentor",
    title: "Researcher",
    university: "University of Wolverhampton",
    country: "UK",
    fields: ["Computer Science", "Research"],
    rating: 4.4,
    image: avatar("Muhammad Kamran Naeem"),
    email: email("Muhammad Kamran Naeem"),
    bio: bioFromFields(["Computer Science", "Research"], "University of Wolverhampton"),
    publications: pubs(["Computer Science", "Research"], "Muhammad Kamran Naeem"),
    featured: false
  },
  {
    id: 58,
    name: "Samiha Hossain",
    type: "mentor",
    title: "Researcher",
    university: "—",
    country: "—",
    fields: ["Research", "Computer Science"],
    rating: 4.3,
    image: avatar("Samiha Hossain"),
    email: email("Samiha Hossain"),
    bio: bioFromFields(["Research", "Computer Science"], "RiTECHS"),
    publications: pubs(["Research", "Computer Science"], "Samiha Hossain"),
    featured: false
  },
  {
    id: 157,
    name: "Dr Qasim AlAjmi",
    type: "mentor",
    title: "Dr",
    university: "—",
    country: "—",
    fields: ["Research", "Academic Studies"],
    rating: 4.3,
    image: avatar("Qasim AlAjmi"),
    email: email("Qasim AlAjmi"),
    bio: bioFromFields(["Research", "Academic Studies"], "RiTECHS"),
    publications: pubs(["Research", "Academic Studies"], "Qasim AlAjmi"),
    featured: false
  },
  {
    id: 163,
    name: "Ragad M Tawafak",
    type: "mentor",
    title: "Researcher",
    university: "—",
    country: "—",
    fields: ["E-government", "Information Systems"],
    rating: 4.4,
    image: avatar("Ragad M Tawafak"),
    email: email("Ragad M Tawafak"),
    bio: bioFromFields(["E-government", "Information Systems"], "RiTECHS"),
    publications: pubs(["E-government", "Information Systems"], "Ragad M Tawafak"),
    featured: false
  },
  {
    id: 165,
    name: "Nahid Hossain",
    type: "mentor",
    title: "Researcher",
    university: "United International University",
    country: "Dhaka, Bangladesh",
    fields: ["Computer Science", "Information Technology"],
    rating: 4.5,
    image: avatar("Nahid Hossain"),
    email: email("Nahid Hossain"),
    bio: bioFromFields(["Computer Science", "Information Technology"], "United International University"),
    publications: pubs(["Computer Science", "Information Technology"], "Nahid Hossain"),
    featured: false
  },
  {
    id: 167,
    name: "Khattab M Ali Alheeti",
    type: "mentor",
    title: "Researcher",
    university: "—",
    country: "—",
    fields: ["Computer Science", "Cybersecurity"],
    rating: 4.4,
    image: avatar("Khattab M Ali Alheeti"),
    email: email("Khattab M Ali Alheeti"),
    bio: bioFromFields(["Computer Science", "Cybersecurity"], "RiTECHS"),
    publications: pubs(["Computer Science", "Cybersecurity"], "Khattab M Ali Alheeti"),
    featured: false
  },
  {
    id: 169,
    name: "Mehdi Gheisari",
    type: "mentor",
    title: "Researcher",
    university: "GZHU",
    country: "—",
    fields: ["Cybersecurity"],
    rating: 4.5,
    image: avatar("Mehdi Gheisari"),
    email: email("Mehdi Gheisari"),
    bio: bioFromFields(["Cybersecurity"], "GZHU"),
    publications: pubs(["Cybersecurity"], "Mehdi Gheisari"),
    featured: false
  },
  {
    id: 173,
    name: "Hussein Jabar Khadim",
    type: "mentor",
    title: "Researcher",
    university: "University of Baghdad",
    country: "Iraq–Baghdad",
    fields: ["Computer Science", "Research"],
    rating: 4.3,
    image: avatar("Hussein Jabar Khadim"),
    email: email("Hussein Jabar Khadim"),
    bio: bioFromFields(["Computer Science", "Research"], "University of Baghdad"),
    publications: pubs(["Computer Science", "Research"], "Hussein Jabar Khadim"),
    featured: false
  },
  {
    id: 177,
    name: "Belal Abdullah Alfuhaidi",
    type: "mentor",
    title: "Researcher",
    university: "University of Science and Technology Sana'a",
    country: "Sana'a, Yemen",
    fields: ["Computer Science", "Information Technology"],
    rating: 4.4,
    image: avatar("Belal Abdullah Alfuhaidi"),
    email: email("Belal Abdullah Alfuhaidi"),
    bio: bioFromFields(["Computer Science", "Information Technology"], "University of Science and Technology Sana'a"),
    publications: pubs(["Computer Science", "Information Technology"], "Belal Abdullah Alfuhaidi"),
    featured: false
  },
  {
    id: 178,
    name: "Mohammed Salah Abood",
    type: "mentor",
    title: "Researcher",
    university: "—",
    country: "—",
    fields: ["Research", "Computer Science"],
    rating: 4.3,
    image: avatar("Mohammed Salah Abood"),
    email: email("Mohammed Salah Abood"),
    bio: bioFromFields(["Research", "Computer Science"], "RiTECHS"),
    publications: pubs(["Research", "Computer Science"], "Mohammed Salah Abood"),
    featured: false
  },
  {
    id: 179,
    name: "Dr. Anish Gupta",
    type: "mentor",
    title: "Dr",
    university: "—",
    country: "—",
    fields: ["Computer Science", "Research"],
    rating: 4.4,
    image: avatar("Anish Gupta"),
    email: email("Anish Gupta"),
    bio: bioFromFields(["Computer Science", "Research"], "RiTECHS"),
    publications: pubs(["Computer Science", "Research"], "Anish Gupta"),
    featured: false
  },
  {
    id: 180,
    name: "Sapna Dewari",
    type: "mentor",
    title: "Researcher",
    university: "—",
    country: "—",
    fields: ["Computer Science", "Research"],
    rating: 4.3,
    image: avatar("Sapna Dewari"),
    email: email("Sapna Dewari"),
    bio: bioFromFields(["Computer Science", "Research"], "RiTECHS"),
    publications: pubs(["Computer Science", "Research"], "Sapna Dewari"),
    featured: false
  },
  {
    id: 206,
    name: "Selim Ahmed",
    type: "mentor",
    title: "Researcher",
    university: "—",
    country: "—",
    fields: ["Research", "Computer Science"],
    rating: 4.2,
    image: avatar("Selim Ahmed"),
    email: email("Selim Ahmed"),
    bio: bioFromFields(["Research", "Computer Science"], "RiTECHS"),
    publications: pubs(["Research", "Computer Science"], "Selim Ahmed"),
    featured: false
  },
  {
    id: 207,
    name: "Subrata Chowdhury",
    type: "mentor",
    title: "Researcher",
    university: "—",
    country: "—",
    fields: ["Research", "Computer Science"],
    rating: 4.2,
    image: avatar("Subrata Chowdhury"),
    email: email("Subrata Chowdhury"),
    bio: bioFromFields(["Research", "Computer Science"], "RiTECHS"),
    publications: pubs(["Research", "Computer Science"], "Subrata Chowdhury"),
    featured: false
  },
  {
    id: 212,
    name: "Ahasanul Karim",
    type: "mentor",
    title: "Researcher",
    university: "Laval University",
    country: "Quebec, Canada",
    fields: ["Computer Science", "Research"],
    rating: 4.4,
    image: avatar("Ahasanul Karim"),
    email: email("Ahasanul Karim"),
    bio: bioFromFields(["Computer Science", "Research"], "Laval University"),
    publications: pubs(["Computer Science", "Research"], "Ahasanul Karim"),
    featured: false
  },
  {
    id: 222,
    name: "Mohammed Amirul Islam",
    type: "mentor",
    title: "Researcher",
    university: "—",
    country: "—",
    fields: ["Research", "Computer Science"],
    rating: 4.2,
    image: avatar("Mohammed Amirul Islam"),
    email: email("Mohammed Amirul Islam"),
    bio: bioFromFields(["Research", "Computer Science"], "RiTECHS"),
    publications: pubs(["Research", "Computer Science"], "Mohammed Amirul Islam"),
    featured: false
  },
  {
    id: 403,
    name: "Md. Iqbal Mahmood",
    type: "mentor",
    title: "Researcher",
    university: "Institute for Molecular Science",
    country: "Okazaki, Japan",
    fields: ["Molecular Science", "Chemistry", "Research"],
    rating: 4.5,
    image: avatar("Md. Iqbal Mahmood"),
    email: email("Md. Iqbal Mahmood"),
    bio: bioFromFields(["Molecular Science", "Chemistry", "Research"], "Institute for Molecular Science"),
    publications: pubs(["Molecular Science", "Chemistry", "Research"], "Md. Iqbal Mahmood"),
    featured: false
  },
  {
    id: 414,
    name: "Muhammed Jamshed Alam Patwary",
    type: "mentor",
    title: "Researcher",
    university: "International Islamic University Chittagong",
    country: "Chittagong, Bangladesh",
    fields: ["Computer Science", "Research"],
    rating: 4.4,
    image: avatar("Muhammed Jamshed Alam Patwary"),
    email: email("Muhammed Jamshed Alam Patwary"),
    bio: bioFromFields(["Computer Science", "Research"], "International Islamic University Chittagong"),
    publications: pubs(["Computer Science", "Research"], "Muhammed Jamshed Alam Patwary"),
    featured: false
  },
  {
    id: 454,
    name: "Pankaj",
    type: "mentor",
    title: "Researcher",
    university: "—",
    country: "Amaravati, India",
    fields: ["Research", "Computer Science"],
    rating: 4.3,
    image: avatar("Pankaj"),
    email: email("Pankaj"),
    bio: bioFromFields(["Research", "Computer Science"], "RiTECHS"),
    publications: pubs(["Research", "Computer Science"], "Pankaj"),
    featured: false
  },
  {
    id: 458,
    name: "Dr. Puranjan Mishra",
    type: "mentor",
    title: "Dr",
    university: "Hong Kong Baptist University",
    country: "Hong Kong",
    fields: ["Computer Science", "Research"],
    rating: 4.5,
    image: avatar("Puranjan Mishra"),
    email: email("Puranjan Mishra"),
    bio: bioFromFields(["Computer Science", "Research"], "Hong Kong Baptist University"),
    publications: pubs(["Computer Science", "Research"], "Puranjan Mishra"),
    featured: false
  },
  {
    id: 480,
    name: "VIKAS VERMA",
    type: "mentor",
    title: "Researcher",
    university: "Kanpur Institute of Technology",
    country: "Kanpur",
    fields: ["Computer Science", "Engineering", "Research"],
    rating: 4.3,
    image: avatar("VIKAS VERMA"),
    email: email("VIKAS VERMA"),
    bio: bioFromFields(["Computer Science", "Engineering", "Research"], "Kanpur Institute of Technology"),
    publications: pubs(["Computer Science", "Engineering", "Research"], "VIKAS VERMA"),
    featured: false
  },
  {
    id: 481,
    name: "Abhishek Vishnoi",
    type: "mentor",
    title: "Researcher",
    university: "Kanpur Institute of Technology",
    country: "Kanpur",
    fields: ["Computer Science", "Engineering", "Research"],
    rating: 4.3,
    image: avatar("Abhishek Vishnoi"),
    email: email("Abhishek Vishnoi"),
    bio: bioFromFields(["Computer Science", "Engineering", "Research"], "Kanpur Institute of Technology"),
    publications: pubs(["Computer Science", "Engineering", "Research"], "Abhishek Vishnoi"),
    featured: false
  },
  {
    id: 504,
    name: "M.M. Hasan Mahfuz",
    type: "mentor",
    title: "Researcher",
    university: "Concordia University",
    country: "Montreal, Canada",
    fields: ["Machine learning", "RF and Microwave Engineering"],
    rating: 4.5,
    image: avatar("M.M. Hasan Mahfuz"),
    email: email("M.M. Hasan Mahfuz"),
    bio: bioFromFields(["Machine learning", "RF and Microwave Engineering"], "Concordia University"),
    publications: pubs(["Machine learning", "RF and Microwave Engineering"], "M.M. Hasan Mahfuz"),
    featured: false
  },
  {
    id: 539,
    name: "Omar",
    type: "mentor",
    title: "Researcher",
    university: "Southern University of Science and Technology",
    country: "China",
    fields: ["Research", "Computer Science", "Engineering"],
    rating: 4.4,
    image: avatar("Omar"),
    email: email("Omar"),
    bio: bioFromFields(["Research", "Computer Science", "Engineering"], "Southern University of Science and Technology"),
    publications: pubs(["Research", "Computer Science", "Engineering"], "Omar"),
    featured: false
  },
  {
    id: 581,
    name: "Roslinda Ramli",
    type: "mentor",
    title: "Researcher",
    university: "KUIS",
    country: "Bangi, Selangor, Malaysia",
    fields: ["Research", "Computer Science"],
    rating: 4.3,
    image: avatar("Roslinda Ramli"),
    email: email("Roslinda Ramli"),
    bio: bioFromFields(["Research", "Computer Science"], "KUIS"),
    publications: pubs(["Research", "Computer Science"], "Roslinda Ramli"),
    featured: false
  },
  {
    id: 592,
    name: "Waheb Abduljabbar Shaif Abdullah",
    type: "mentor",
    title: "Researcher",
    university: "Birmingham City University",
    country: "UK",
    fields: ["Computer Science", "Research"],
    rating: 4.4,
    image: avatar("Waheb Abduljabbar Shaif Abdullah"),
    email: email("Waheb Abduljabbar Shaif Abdullah"),
    bio: bioFromFields(["Computer Science", "Research"], "Birmingham City University"),
    publications: pubs(["Computer Science", "Research"], "Waheb Abduljabbar Shaif Abdullah"),
    featured: false
  },
  {
    id: 604,
    name: "Dr R Sujatha",
    type: "mentor",
    title: "Dr",
    university: "Vellore Institute of Technology",
    country: "India",
    fields: ["Computer Science", "Research", "Engineering"],
    rating: 4.5,
    image: avatar("R Sujatha"),
    email: email("R Sujatha"),
    bio: bioFromFields(["Computer Science", "Research", "Engineering"], "Vellore Institute of Technology"),
    publications: pubs(["Computer Science", "Research", "Engineering"], "R Sujatha"),
    featured: false
  },
  {
    id: 610,
    name: "Dr. Santhana Krishnan",
    type: "mentor",
    title: "Dr",
    university: "University of Technology Malaysia",
    country: "Malaysia",
    fields: ["Bioelectrochemical systems", "Bio-energy", "Bioreactors", "Electro catalyst"],
    rating: 4.5,
    image: avatar("Santhana Krishnan"),
    email: email("Santhana Krishnan"),
    bio: bioFromFields(["Bioelectrochemical systems", "Bio-energy", "Bioreactors"], "University of Technology Malaysia"),
    publications: pubs(["Bioelectrochemical systems", "Bio-energy", "Bioreactors"], "Santhana Krishnan"),
    featured: false
  },
  {
    id: 615,
    name: "Zeashan Hameed Khan",
    type: "mentor",
    title: "Researcher",
    university: "Air University, Islamabad",
    country: "Pakistan",
    fields: ["Computer Science", "Research"],
    rating: 4.3,
    image: avatar("Zeashan Hameed Khan"),
    email: email("Zeashan Hameed Khan"),
    bio: bioFromFields(["Computer Science", "Research"], "Air University, Islamabad"),
    publications: pubs(["Computer Science", "Research"], "Zeashan Hameed Khan"),
    featured: false
  },
  {
    id: 616,
    name: "Ashis Kumar Mandal",
    type: "mentor",
    title: "Researcher",
    university: "Hajee Mohammad Danesh Science and Technology University",
    country: "Bangladesh",
    fields: ["Computer Science", "Research", "Engineering"],
    rating: 4.3,
    image: avatar("Ashis Kumar Mandal"),
    email: email("Ashis Kumar Mandal"),
    bio: bioFromFields(["Computer Science", "Research", "Engineering"], "Hajee Mohammad Danesh Science and Technology University"),
    publications: pubs(["Computer Science", "Research", "Engineering"], "Ashis Kumar Mandal"),
    featured: false
  },
  {
    id: 617,
    name: "Md. Kafiul Islam",
    type: "mentor",
    title: "Researcher",
    university: "Independent University, Bangladesh",
    country: "Bangladesh",
    fields: ["BCI classification", "Machine learning"],
    rating: 4.5,
    image: avatar("Md. Kafiul Islam"),
    email: email("Md. Kafiul Islam"),
    bio: bioFromFields(["BCI classification", "Machine learning"], "Independent University, Bangladesh"),
    publications: pubs(["BCI classification", "Machine learning"], "Md. Kafiul Islam"),
    featured: false
  },
  {
    id: 618,
    name: "Mohiuddin Ahmad",
    type: "mentor",
    title: "Researcher",
    university: "Khulna University of Engineering & Technology (KUET)",
    country: "Khulna, Bangladesh",
    fields: ["Computer Science", "Engineering", "Research"],
    rating: 4.4,
    image: avatar("Mohiuddin Ahmad"),
    email: email("Mohiuddin Ahmad"),
    bio: bioFromFields(["Computer Science", "Engineering", "Research"], "Khulna University of Engineering & Technology"),
    publications: pubs(["Computer Science", "Engineering", "Research"], "Mohiuddin Ahmad"),
    featured: false
  },
  {
    id: 619,
    name: "Dr. Md. Rakibul Hoque",
    type: "mentor",
    title: "Dr",
    university: "University of Dhaka",
    country: "Dhaka, Bangladesh",
    fields: ["Computer Science", "Research"],
    rating: 4.5,
    image: avatar("Md. Rakibul Hoque"),
    email: email("Md. Rakibul Hoque"),
    bio: bioFromFields(["Computer Science", "Research"], "University of Dhaka"),
    publications: pubs(["Computer Science", "Research"], "Md. Rakibul Hoque"),
    featured: false
  },
  {
    id: 620,
    name: "Dr. M. F. Mridha",
    type: "mentor",
    title: "Dr",
    university: "American International University-Bangladesh (AIUB)",
    country: "Bangladesh",
    fields: ["Machine learning", "Data mining", "BCI classification", "Data Science"],
    rating: 4.6,
    image: avatar("M. F. Mridha"),
    email: email("M. F. Mridha"),
    bio: bioFromFields(["Machine learning", "Data mining", "BCI classification"], "American International University-Bangladesh"),
    publications: pubs(["Machine learning", "Data mining", "BCI classification"], "M. F. Mridha"),
    featured: false
  },
  {
    id: 624,
    name: "Adnan Daud Khan",
    type: "mentor",
    title: "Researcher",
    university: "University of Engineering & Technology Peshawar",
    country: "Pakistan",
    fields: ["Computer Science", "Engineering", "Research"],
    rating: 4.3,
    image: avatar("Adnan Daud Khan"),
    email: email("Adnan Daud Khan"),
    bio: bioFromFields(["Computer Science", "Engineering", "Research"], "University of Engineering & Technology Peshawar"),
    publications: pubs(["Computer Science", "Engineering", "Research"], "Adnan Daud Khan"),
    featured: false
  },
  {
    id: 629,
    name: "Dr Mohammad Sarwar Morshed",
    type: "mentor",
    title: "Dr",
    university: "Ahsanullah University of Science and Technology",
    country: "Dhaka, Bangladesh",
    fields: ["Computer Science", "Research", "Engineering"],
    rating: 4.4,
    image: avatar("Mohammad Sarwar Morshed"),
    email: email("Mohammad Sarwar Morshed"),
    bio: bioFromFields(["Computer Science", "Research", "Engineering"], "Ahsanullah University of Science and Technology"),
    publications: pubs(["Computer Science", "Research", "Engineering"], "Mohammad Sarwar Morshed"),
    featured: false
  },
  {
    id: 650,
    name: "Bryar Hassan",
    type: "mentor",
    title: "Researcher",
    university: "Charmo University",
    country: "Sulaimani, Iraq",
    fields: ["Computer Science", "Research"],
    rating: 4.3,
    image: avatar("Bryar Hassan"),
    email: email("Bryar Hassan"),
    bio: bioFromFields(["Computer Science", "Research"], "Charmo University"),
    publications: pubs(["Computer Science", "Research"], "Bryar Hassan"),
    featured: false
  },
  {
    id: 665,
    name: "Amin Noroozi Fakhabi",
    type: "mentor",
    title: "Researcher",
    university: "The University of Wolverhampton",
    country: "Wolverhampton, UK",
    fields: ["Computer Science", "Research"],
    rating: 4.4,
    image: avatar("Amin Noroozi Fakhabi"),
    email: email("Amin Noroozi Fakhabi"),
    bio: bioFromFields(["Computer Science", "Research"], "The University of Wolverhampton"),
    publications: pubs(["Computer Science", "Research"], "Amin Noroozi Fakhabi"),
    featured: false
  },
  {
    id: 749,
    name: "Md Tarikul",
    type: "mentor",
    title: "Researcher",
    university: "University of Greenwich",
    country: "United Kingdom",
    fields: ["Computer Science", "Research"],
    rating: 4.4,
    image: avatar("Md Tarikul"),
    email: email("Md Tarikul"),
    bio: bioFromFields(["Computer Science", "Research"], "University of Greenwich"),
    publications: pubs(["Computer Science", "Research"], "Md Tarikul"),
    featured: false
  }
];

// ============ MENTEES (Optional - can be filtered out) ============
export const mentees: Mentor[] = [
  {id: 15, name: "Nafees Bin Zaman", type: "mentee", title: "Researcher", university: "Universitat de Girona", country: "Spain", fields: ["Computer Science"], rating: 0, image: avatar("Nafees Bin Zaman"), email: email("Nafees Bin Zaman"), bio: "PhD candidate seeking research guidance in computer science.", publications: [], featured: false},
  {id: 24, name: "Nazmus Sakib Bin Khair", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Nazmus Sakib Bin Khair"), email: email("Nazmus Sakib Bin Khair"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 25, name: "Saydul Akbar Murad", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Saydul Akbar Murad"), email: email("Saydul Akbar Murad"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 27, name: "Md Shamimul Islam", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Md Shamimul Islam"), email: email("Md Shamimul Islam"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 31, name: "N H M Arafat", type: "mentee", title: "Researcher", university: "Henan Polytechnic University", country: "China", fields: ["Engineering"], rating: 0, image: avatar("N H M Arafat"), email: email("N H M Arafat"), bio: "PhD candidate at Henan Polytechnic University seeking research mentorship.", publications: [], featured: false},
  {id: 44, name: "Abdur Rahman Emon", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Abdur Rahman Emon"), email: email("Abdur Rahman Emon"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 47, name: "Sabbir Shikder Orid", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Sabbir Shikder Orid"), email: email("Sabbir Shikder Orid"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 50, name: "Habiba", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Habiba"), email: email("Habiba"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 55, name: "S. M. Raihan Gafur", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("S. M. Raihan Gafur"), email: email("S. M. Raihan Gafur"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 57, name: "Faiaz Ben Reza", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Faiaz Ben Reza"), email: email("Faiaz Ben Reza"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 60, name: "Sumaiya Sultana", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Sumaiya Sultana"), email: email("Sumaiya Sultana"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 63, name: "Rakib Hossain Ivan", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Rakib Hossain Ivan"), email: email("Rakib Hossain Ivan"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 64, name: "Tazdik Hossain", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Tazdik Hossain"), email: email("Tazdik Hossain"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 65, name: "Nadim Hossain", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Nadim Hossain"), email: email("Nadim Hossain"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 66, name: "Khandaker Raiyan Rahman", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Khandaker Raiyan Rahman"), email: email("Khandaker Raiyan Rahman"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 67, name: "Debashish Dey", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Debashish Dey"), email: email("Debashish Dey"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 68, name: "Sayeed Hasan", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Sayeed Hasan"), email: email("Sayeed Hasan"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 69, name: "Faieq Hamim", type: "mentee", title: "Researcher", university: "—", country: "Dhaka, Bangladesh", fields: ["Computer Science"], rating: 0, image: avatar("Faieq Hamim"), email: email("Faieq Hamim"), bio: "Mentee based in Dhaka, Bangladesh, seeking research guidance.", publications: [], featured: false},
  {id: 70, name: "Sanjida Hoque", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Sanjida Hoque"), email: email("Sanjida Hoque"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 72, name: "Adnan Sami", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Adnan Sami"), email: email("Adnan Sami"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 73, name: "Rahatul Ashekin Ashik", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Rahatul Ashekin Ashik"), email: email("Rahatul Ashekin Ashik"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 74, name: "Arnab Das", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Arnab Das"), email: email("Arnab Das"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 75, name: "Khandokar Shadman Shayer", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Khandokar Shadman Shayer"), email: email("Khandokar Shadman Shayer"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 76, name: "Neamul Ibne Monir Rahim", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Neamul Ibne Monir Rahim"), email: email("Neamul Ibne Monir Rahim"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 77, name: "Jannatuil Ferdouse Jannat", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Jannatuil Ferdouse Jannat"), email: email("Jannatuil Ferdouse Jannat"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 78, name: "Anik Sarkar", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Anik Sarkar"), email: email("Anik Sarkar"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 79, name: "ABU JUNAED MOHD ASIF", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("ABU JUNAED MOHD ASIF"), email: email("ABU JUNAED MOHD ASIF"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 80, name: "Paul Rinika", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Paul Rinika"), email: email("Paul Rinika"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 81, name: "Rahman Md.Tahsinur", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Rahman Md.Tahsinur"), email: email("Rahman Md.Tahsinur"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 82, name: "Md. Abu Zehad Foysal", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Md. Abu Zehad Foysal"), email: email("Md. Abu Zehad Foysal"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 83, name: "Atanu Das", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Atanu Das"), email: email("Atanu Das"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 86, name: "Saiydur Rahman", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Saiydur Rahman"), email: email("Saiydur Rahman"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 88, name: "Md Shamim Shakil", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Md Shamim Shakil"), email: email("Md Shamim Shakil"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 89, name: "adnans", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("adnans"), email: email("adnans"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 90, name: "Sumon roy", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Sumon roy"), email: email("Sumon roy"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 91, name: "Prajna Shirsho Shome", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Prajna Shirsho Shome"), email: email("Prajna Shirsho Shome"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 92, name: "Tanzim Zaman", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Tanzim Zaman"), email: email("Tanzim Zaman"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 93, name: "Maweza Nargis Haider", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Maweza Nargis Haider"), email: email("Maweza Nargis Haider"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 94, name: "Minhazur Rahman", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Minhazur Rahman"), email: email("Minhazur Rahman"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 95, name: "FAZLA IMAM DIP", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("FAZLA IMAM DIP"), email: email("FAZLA IMAM DIP"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 96, name: "Md. Ibrahim Bahadur", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Md. Ibrahim Bahadur"), email: email("Md. Ibrahim Bahadur"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 97, name: "Rashedul Haque", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Rashedul Haque"), email: email("Rashedul Haque"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 98, name: "Nedul Kumer Roy", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Nedul Kumer Roy"), email: email("Nedul Kumer Roy"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 99, name: "TASRIFUL HAQUE", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("TASRIFUL HAQUE"), email: email("TASRIFUL HAQUE"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 100, name: "Md Abu Sufian", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Md Abu Sufian"), email: email("Md Abu Sufian"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 101, name: "Fatin Istiak Rahman", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Fatin Istiak Rahman"), email: email("Fatin Istiak Rahman"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 104, name: "Md. Afnan Rahman Arnab", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Md. Afnan Rahman Arnab"), email: email("Md. Afnan Rahman Arnab"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 105, name: "Md.Al-Samiul Amin Rishat", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Md.Al-Samiul Amin Rishat"), email: email("Md.Al-Samiul Amin Rishat"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 107, name: "Umar Faruque Ibne Ariff", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Umar Faruque Ibne Ariff"), email: email("Umar Faruque Ibne Ariff"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 108, name: "Kaushik Biswas", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Kaushik Biswas"), email: email("Kaushik Biswas"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 110, name: "Diganto", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Diganto"), email: email("Diganto"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 111, name: "Auditi Roy", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Auditi Roy"), email: email("Auditi Roy"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 112, name: "Islam Sazzadul", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Islam Sazzadul"), email: email("Islam Sazzadul"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 113, name: "Shahed Chowdhury Omi", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Shahed Chowdhury Omi"), email: email("Shahed Chowdhury Omi"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 114, name: "tahsinul hoque", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("tahsinul hoque"), email: email("tahsinul hoque"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 115, name: "Turny Tania Tasmim", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Turny Tania Tasmim"), email: email("Turny Tania Tasmim"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 117, name: "Maliha Tasnuva", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Maliha Tasnuva"), email: email("Maliha Tasnuva"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 118, name: "Niloy Roy", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Niloy Roy"), email: email("Niloy Roy"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 119, name: "Tahmeed Mahbub", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Tahmeed Mahbub"), email: email("Tahmeed Mahbub"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 120, name: "Mohammad Nur Newaz Oyon", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Mohammad Nur Newaz Oyon"), email: email("Mohammad Nur Newaz Oyon"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 121, name: "MD. SAHIB AL MUBIN NILOY", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("MD. SAHIB AL MUBIN NILOY"), email: email("MD. SAHIB AL MUBIN NILOY"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 122, name: "SAZID AL FARABI", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("SAZID AL FARABI"), email: email("SAZID AL FARABI"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 124, name: "Abdus Sakur", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Abdus Sakur"), email: email("Abdus Sakur"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 125, name: "Rashedul Islam", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Rashedul Islam"), email: email("Rashedul Islam"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 128, name: "Hasan Sanjary Islam", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Hasan Sanjary Islam"), email: email("Hasan Sanjary Islam"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 129, name: "Mehenaz Tabassoom", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Mehenaz Tabassoom"), email: email("Mehenaz Tabassoom"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 130, name: "Noor A Aysha", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Noor A Aysha"), email: email("Noor A Aysha"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 132, name: "Tabassum Lamia Tonni", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Tabassum Lamia Tonni"), email: email("Tabassum Lamia Tonni"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 136, name: "Sadia Hossain", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Sadia Hossain"), email: email("Sadia Hossain"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 138, name: "Avijit Paul", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Avijit Paul"), email: email("Avijit Paul"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 140, name: "MD. ASIF B. ABEDIN", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("MD. ASIF B. ABEDIN"), email: email("MD. ASIF B. ABEDIN"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 141, name: "Farjana Ahmed", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Farjana Ahmed"), email: email("Farjana Ahmed"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 142, name: "Rokan Chowdhury Onick", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Rokan Chowdhury Onick"), email: email("Rokan Chowdhury Onick"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 143, name: "Ali Muharram", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Ali Muharram"), email: email("Ali Muharram"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 145, name: "Muhaiminul Ashrafee", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Muhaiminul Ashrafee"), email: email("Muhaiminul Ashrafee"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 146, name: "Jalal Uddin Md Akbar", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Jalal Uddin Md Akbar"), email: email("Jalal Uddin Md Akbar"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 148, name: "Zerin Tasnim", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Zerin Tasnim"), email: email("Zerin Tasnim"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 150, name: "Shawon", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Shawon"), email: email("Shawon"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 153, name: "Faiyaz Shahrear", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Faiyaz Shahrear"), email: email("Faiyaz Shahrear"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 154, name: "Md Shamsul Arifin", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Md Shamsul Arifin"), email: email("Md Shamsul Arifin"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 156, name: "Muhammad Al Amin Rifat", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Muhammad Al Amin Rifat"), email: email("Muhammad Al Amin Rifat"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 158, name: "Shorif Ahmed Afridi Mozumder", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Shorif Ahmed Afridi Mozumder"), email: email("Shorif Ahmed Afridi Mozumder"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 160, name: "Rafid Shariar Rimu", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Rafid Shariar Rimu"), email: email("Rafid Shariar Rimu"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 170, name: "Akwinder Kaur", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Akwinder Kaur"), email: email("Akwinder Kaur"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 175, name: "NOOR E FAHMIDA", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("NOOR E FAHMIDA"), email: email("NOOR E FAHMIDA"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 176, name: "MAGED RFEQALLAH", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("MAGED RFEQALLAH"), email: email("MAGED RFEQALLAH"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 182, name: "Jatin Aditya", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Jatin Aditya"), email: email("Jatin Aditya"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 190, name: "MD SAEF ULLAH ULLAH", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("MD SAEF ULLAH ULLAH"), email: email("MD SAEF ULLAH ULLAH"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 195, name: "Mizanur Rahman", type: "mentee", title: "Researcher", university: "Universiti Malaysia Pahang", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Mizanur Rahman"), email: email("Mizanur Rahman"), bio: "Mentee at Universiti Malaysia Pahang seeking research guidance.", publications: [], featured: false},
  {id: 196, name: "Md Jahan Ali", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Md Jahan Ali"), email: email("Md Jahan Ali"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 198, name: "Md. Mobarak Hossain Jewel", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Md. Mobarak Hossain Jewel"), email: email("Md. Mobarak Hossain Jewel"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false},
  {id: 461, name: "Gopa Nandikes P", type: "mentee", title: "Researcher", university: "SRM University-AP", country: "Andhra Pradesh", fields: ["Computer Science"], rating: 0, image: avatar("Gopa Nandikes P"), email: email("Gopa Nandikes P"), bio: "Mentee at SRM University-AP seeking research guidance.", publications: [], featured: false},
  {id: 532, name: "Chengjuan Ren", type: "mentee", title: "Researcher", university: "Baoji University", country: "China", fields: ["Computer Science"], rating: 0, image: avatar("Chengjuan Ren"), email: email("Chengjuan Ren"), bio: "Mentee at Baoji University seeking research guidance.", publications: [], featured: false},
  {id: 533, name: "Annajiat Alim Rasel", type: "mentee", title: "Researcher", university: "Brac University", country: "Dhaka", fields: ["Computer Science"], rating: 0, image: avatar("Annajiat Alim Rasel"), email: email("Annajiat Alim Rasel"), bio: "Mentee at Brac University seeking research guidance.", publications: [], featured: false},
  {id: 541, name: "Joseph Isinka", type: "mentee", title: "Researcher", university: "Wolverhampton University", country: "Reading", fields: ["Computer Science"], rating: 0, image: avatar("Joseph Isinka"), email: email("Joseph Isinka"), bio: "Mentee at Wolverhampton University seeking research guidance.", publications: [], featured: false},
  {id: 542, name: "Mahmood Abdullah Moqbel Bazel", type: "mentee", title: "Researcher", university: "University Utara Malaysia", country: "Malaysia", fields: ["Computer Science"], rating: 0, image: avatar("Mahmood Abdullah Moqbel Bazel"), email: email("Mahmood Abdullah Moqbel Bazel"), bio: "Mentee at University Utara Malaysia seeking research guidance.", publications: [], featured: false},
  {id: 545, name: "Shikha Ratti", type: "mentee", title: "Researcher", university: "—", country: "Wolverhampton", fields: ["Computer Science"], rating: 0, image: avatar("Shikha Ratti"), email: email("Shikha Ratti"), bio: "Mentee based in Wolverhampton seeking research guidance.", publications: [], featured: false},
  {id: 574, name: "Anuj Kumar", type: "mentee", title: "Researcher", university: "—", country: "Wolverhampton", fields: ["Computer Science"], rating: 0, image: avatar("Anuj Kumar"), email: email("Anuj Kumar"), bio: "Mentee based in Wolverhampton seeking research guidance.", publications: [], featured: false},
  {id: 575, name: "samia NASIRI", type: "mentee", title: "Researcher", university: "University of Moulay Ismail", country: "Morocco", fields: ["Computer Science"], rating: 0, image: avatar("samia NASIRI"), email: email("samia NASIRI"), bio: "Mentee at University of Moulay Ismail seeking research guidance.", publications: [], featured: false},
  {id: 580, name: "Maliha Zaman", type: "mentee", title: "Researcher", university: "University of Asia Pacific", country: "Dhaka", fields: ["Computer Science"], rating: 0, image: avatar("Maliha Zaman"), email: email("Maliha Zaman"), bio: "Mentee at University of Asia Pacific seeking research guidance.", publications: [], featured: false},
  {id: 584, name: "Sadia Tamim Dip", type: "mentee", title: "Researcher", university: "University of Asia Pacific", country: "Dhaka, Bangladesh", fields: ["Computer Science"], rating: 0, image: avatar("Sadia Tamim Dip"), email: email("Sadia Tamim Dip"), bio: "Mentee at University of Asia Pacific seeking research guidance.", publications: [], featured: false},
  {id: 589, name: "Redwana Hai Momo", type: "mentee", title: "Researcher", university: "University of Asia Pacific", country: "Dhaka, Bangladesh", fields: ["Computer Science"], rating: 0, image: avatar("Redwana Hai Momo"), email: email("Redwana Hai Momo"), bio: "Mentee at University of Asia Pacific seeking research guidance.", publications: [], featured: false},
  {id: 590, name: "Tasnim Jahin Mowla", type: "mentee", title: "Researcher", university: "University of Asia Pacific", country: "Dhaka, Bangladesh", fields: ["Computer Science"], rating: 0, image: avatar("Tasnim Jahin Mowla"), email: email("Tasnim Jahin Mowla"), bio: "Mentee at University of Asia Pacific seeking research guidance.", publications: [], featured: false},
  {id: 591, name: "MD. AHASAN HABIB NAHID", type: "mentee", title: "Researcher", university: "University of Asia Pacific", country: "Dhaka, Bangladesh", fields: ["Computer Science"], rating: 0, image: avatar("MD. AHASAN HABIB NAHID"), email: email("MD. AHASAN HABIB NAHID"), bio: "Mentee at University of Asia Pacific seeking research guidance.", publications: [], featured: false},
  {id: 593, name: "Injamul Haque", type: "mentee", title: "Researcher", university: "University of Asia Pacific", country: "Dhaka, Bangladesh", fields: ["Computer Science"], rating: 0, image: avatar("Injamul Haque"), email: email("Injamul Haque"), bio: "Mentee at University of Asia Pacific seeking research guidance.", publications: [], featured: false},
  {id: 594, name: "Tasnim Sabiha", type: "mentee", title: "Researcher", university: "UAP", country: "Dhaka", fields: ["Computer Science"], rating: 0, image: avatar("Tasnim Sabiha"), email: email("Tasnim Sabiha"), bio: "Mentee at UAP seeking research guidance.", publications: [], featured: false},
  {id: 595, name: "Dhanonjoy Howlader", type: "mentee", title: "Researcher", university: "UAP", country: "Dhaka", fields: ["Computer Science"], rating: 0, image: avatar("Dhanonjoy Howlader"), email: email("Dhanonjoy Howlader"), bio: "Mentee at UAP seeking research guidance.", publications: [], featured: false},
  {id: 596, name: "Tanjim Islam", type: "mentee", title: "Researcher", university: "—", country: "Dhaka, Bangladesh", fields: ["Computer Science"], rating: 0, image: avatar("Tanjim Islam"), email: email("Tanjim Islam"), bio: "Mentee based in Dhaka seeking research guidance.", publications: [], featured: false},
  {id: 600, name: "Kazi Shabbin Hossain", type: "mentee", title: "Researcher", university: "—", country: "Jigatola 68/5(B)", fields: ["Computer Science"], rating: 0, image: avatar("Kazi Shabbin Hossain"), email: email("Kazi Shabbin Hossain"), bio: "Mentee based in Jigatola seeking research guidance.", publications: [], featured: false},
  {id: 601, name: "EISSA MOHAMMED ABDO GHALEB", type: "mentee", title: "Researcher", university: "Peshawar University", country: "Yemen", fields: ["Computer Science"], rating: 0, image: avatar("EISSA MOHAMMED ABDO GHALEB"), email: email("EISSA MOHAMMED ABDO GHALEB"), bio: "Mentee at Peshawar University seeking research guidance.", publications: [], featured: false},
  {id: 602, name: "Nazmun Nahar", type: "mentee", title: "Researcher", university: "Green University of Bangladesh", country: "Khulna, Bangladesh", fields: ["Computer Science"], rating: 0, image: avatar("Nazmun Nahar"), email: email("Nazmun Nahar"), bio: "Mentee at Green University of Bangladesh seeking research guidance.", publications: [], featured: false},
  {id: 621, name: "Ferdib-Al-Islam", type: "mentee", title: "Researcher", university: "Northern University of Business and Technology Khulna", country: "Khulna, Bangladesh", fields: ["Deep Learning", "Machine learning", "IoT", "Data Science"], rating: 0, image: avatar("Ferdib-Al-Islam"), email: email("Ferdib-Al-Islam"), bio: "Mentee at Northern University of Business and Technology Khulna seeking research guidance in Deep Learning and Machine Learning.", publications: [], featured: false},
  {id: 627, name: "J D Milton", type: "mentee", title: "Researcher", university: "University of Science And Technology Chittagong", country: "Chattagram, Bangladesh", fields: ["Computer Science"], rating: 0, image: avatar("J D Milton"), email: email("J D Milton"), bio: "Mentee at University of Science And Technology Chittagong seeking research guidance.", publications: [], featured: false},
  {id: 628, name: "MOYENUL HASAN", type: "mentee", title: "Researcher", university: "Sonargaon University", country: "Dhaka, Bangladesh", fields: ["Computer Science"], rating: 0, image: avatar("MOYENUL HASAN"), email: email("MOYENUL HASAN"), bio: "Mentee at Sonargaon University seeking research guidance.", publications: [], featured: false},
  {id: 632, name: "Olaoluwa Agbeja", type: "mentee", title: "Researcher", university: "GRADX", country: "United Kingdom", fields: ["Computer Science"], rating: 0, image: avatar("Olaoluwa Agbeja"), email: email("Olaoluwa Agbeja"), bio: "Mentee at GRADX seeking research guidance.", publications: [], featured: false},
  {id: 633, name: "Olayinka Oladele", type: "mentee", title: "Researcher", university: "University of Wolverhampton", country: "Wolverhampton", fields: ["Computer Science"], rating: 0, image: avatar("Olayinka Oladele"), email: email("Olayinka Oladele"), bio: "Mentee at University of Wolverhampton seeking research guidance.", publications: [], featured: false},
  {id: 634, name: "Odiri Teddie Adamu", type: "mentee", title: "Researcher", university: "University of Wolverhampton", country: "United Kingdom", fields: ["Computer Science"], rating: 0, image: avatar("Odiri Teddie Adamu"), email: email("Odiri Teddie Adamu"), bio: "Mentee at University of Wolverhampton seeking research guidance.", publications: [], featured: false},
  {id: 635, name: "Abhijit Kumar Dutta", type: "mentee", title: "Researcher", university: "Computer Science", country: "Wolverhampton, UK", fields: ["Computer Science"], rating: 0, image: avatar("Abhijit Kumar Dutta"), email: email("Abhijit Kumar Dutta"), bio: "Mentee in Computer Science based in Wolverhampton seeking research guidance.", publications: [], featured: false},
  {id: 636, name: "Lakshitha Lokuge", type: "mentee", title: "Researcher", university: "University of Wolverhampton (MSc CS)", country: "Wolverhampton", fields: ["Computer Science"], rating: 0, image: avatar("Lakshitha Lokuge"), email: email("Lakshitha Lokuge"), bio: "Mentee pursuing MSc CS at University of Wolverhampton seeking research guidance.", publications: [], featured: false},
  {id: 641, name: "Mohamad Ibrahim", type: "mentee", title: "Researcher", university: "University of Wolverhampton and Derby", country: "Kettering", fields: ["Computer Science"], rating: 0, image: avatar("Mohamad Ibrahim"), email: email("Mohamad Ibrahim"), bio: "Mentee at University of Wolverhampton and Derby seeking research guidance.", publications: [], featured: false},
  {id: 646, name: "Ademola Gabriel Popoola", type: "mentee", title: "Researcher", university: "University of Wolverhampton", country: "Wolverhampton", fields: ["Computer Science"], rating: 0, image: avatar("Ademola Gabriel Popoola"), email: email("Ademola Gabriel Popoola"), bio: "Mentee at University of Wolverhampton seeking research guidance.", publications: [], featured: false},
  {id: 647, name: "BALU SREE HARSHA VEJANDLA", type: "mentee", title: "Researcher", university: "University of Wolverhampton", country: "Wolverhampton", fields: ["Computer Science"], rating: 0, image: avatar("BALU SREE HARSHA VEJANDLA"), email: email("BALU SREE HARSHA VEJANDLA"), bio: "Mentee at University of Wolverhampton seeking research guidance.", publications: [], featured: false},
  {id: 648, name: "Dipesh Thapa", type: "mentee", title: "Researcher", university: "University of Wolverhampton", country: "Wolverhampton, UK", fields: ["Digital Forensics", "Wireless networks", "Cybersecurity", "IoT"], rating: 0, image: avatar("Dipesh Thapa"), email: email("Dipesh Thapa"), bio: "Mentee at University of Wolverhampton seeking research guidance in Digital Forensics and Cybersecurity.", publications: [], featured: false},
  {id: 651, name: "Khubaib Ahmed", type: "mentee", title: "Researcher", university: "University of Wolverhampton", country: "United Kingdom", fields: ["Computer Science"], rating: 0, image: avatar("Khubaib Ahmed"), email: email("Khubaib Ahmed"), bio: "Mentee at University of Wolverhampton seeking research guidance.", publications: [], featured: false},
  {id: 652, name: "Junaid Muzaffar", type: "mentee", title: "Researcher", university: "University of Wolverhampton", country: "Wolverhampton", fields: ["Reinforcement Learning", "Data Science", "Deep Learning", "Machine learning"], rating: 0, image: avatar("Junaid Muzaffar"), email: email("Junaid Muzaffar"), bio: "Mentee at University of Wolverhampton seeking research guidance in Reinforcement Learning and Machine Learning.", publications: [], featured: false},
  {id: 659, name: "Hatim", type: "mentee", title: "Researcher", university: "University of Wolverhampton", country: "Wolverhampton", fields: ["Computer Science"], rating: 0, image: avatar("Hatim"), email: email("Hatim"), bio: "Mentee at University of Wolverhampton seeking research guidance.", publications: [], featured: false},
  {id: 661, name: "Aniledio", type: "mentee", title: "Researcher", university: "University of Wolverhampton", country: "Birmingham", fields: ["Computer Science"], rating: 0, image: avatar("Aniledio"), email: email("Aniledio"), bio: "Mentee at University of Wolverhampton seeking research guidance.", publications: [], featured: false},
  {id: 663, name: "Salman Abdulrazak", type: "mentee", title: "Researcher", university: "University of Wolverhampton", country: "Wolverhampton", fields: ["Computer Science"], rating: 0, image: avatar("Salman Abdulrazak"), email: email("Salman Abdulrazak"), bio: "Mentee at University of Wolverhampton seeking research guidance.", publications: [], featured: false},
  {id: 666, name: "MOHOMED FAIROOS MOHOMED AATHIF", type: "mentee", title: "Researcher", university: "Wolverhampton University", country: "Wolverhampton", fields: ["Computer Science"], rating: 0, image: avatar("MOHOMED FAIROOS MOHOMED AATHIF"), email: email("MOHOMED FAIROOS MOHOMED AATHIF"), bio: "Mentee at Wolverhampton University seeking research guidance.", publications: [], featured: false},
  {id: 670, name: "brajan bartosik", type: "mentee", title: "Researcher", university: "sandwell college", country: "Birmingham", fields: ["Computer Science"], rating: 0, image: avatar("brajan bartosik"), email: email("brajan bartosik"), bio: "Mentee at sandwell college seeking research guidance.", publications: [], featured: false},
  {id: 672, name: "Ahmed Alanazi", type: "mentee", title: "Researcher", university: "—", country: "USA", fields: ["Computer Science"], rating: 0, image: avatar("Ahmed Alanazi"), email: email("Ahmed Alanazi"), bio: "Mentee based in USA seeking research guidance.", publications: [], featured: false},
  {id: 698, name: "Sayeda Sadia Alam", type: "mentee", title: "Researcher", university: "JU", country: "UK", fields: ["Computer Science"], rating: 0, image: avatar("Sayeda Sadia Alam"), email: email("Sayeda Sadia Alam"), bio: "Mentee from JU based in UK seeking research guidance.", publications: [], featured: false},
  {id: 712, name: "Sze Wei Tan", type: "mentee", title: "Researcher", university: "—", country: "—", fields: ["Computer Science"], rating: 0, image: avatar("Sze Wei Tan"), email: email("Sze Wei Tan"), bio: "Mentee seeking academic guidance and research support.", publications: [], featured: false}
];

// Helper export to get only mentors (for the MentorsView component)
export const mentorsOnly = mentors.filter(m => m.type === "mentor");

// Stats helper
export const memberStats = {
  total: mentors.length + mentees.length,
  mentors: mentors.length,
  mentees: mentees.length,
  countries: Array.from(new Set([...mentors, ...mentees].map(m => m.country).filter(c => c && c !== "—"))).length
};
